# Generated by Django 5.0.6 on 2026-08-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPS_Toll_app', '0002_alter_trip_date_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
